version: '3'
services:
  repository:
    image: sonatype/nexus3
    ports:
      - 8081:8081
    volumes:
      - nexus-data:/nexus-data    
  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf 
      - sonarqube_data:/opt/sonarqube/data        
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
      - 50000:50000
    links:
      - repository
      - sonarqube
    volumes:
      - 'jenkins_data:/jenkins_config'
      - /var/run/docker.sock:/var/run/docker.sock
  
volumes:
  jenkins_data:
    driver: local
  nexus-data:
    driver: local  
  sonarqube_conf:
    driver: local
  sonarqube_data:
    driver: local  